FROM rust:1.90.0-bullseye AS builder
WORKDIR /usr/src/gravivol
COPY . .
RUN cargo install --path .

FROM debian:bullseye-slim
COPY --from=builder /usr/local/cargo/bin/gravivol /usr/local/bin/gravivol
CMD ["gravivol"]